# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuserprofile',
            name='tag',
            field=models.CharField(default='systemuserprofile', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tag',
            field=models.CharField(default='userprofile', max_length=20),
            preserve_default=False,
        ),
    ]
