# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160704_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuserprofile',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tag',
        ),
        migrations.AddField(
            model_name='myuser',
            name='tag',
            field=models.CharField(default='systemuser', max_length=20),
            preserve_default=False,
        ),
    ]
