# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160704_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='tag',
        ),
        migrations.AddField(
            model_name='myuser',
            name='type',
            field=models.CharField(default='common_user', max_length=20),
        ),
    ]
