# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160705_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='type',
            new_name='user_type',
        ),
    ]
