# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-16 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='change_data',
            new_name='change_date',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
