# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApkVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=200)),
                ('create_data', models.DateField(blank=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
